services:
  grafana:
    image: grafana/grafana-oss:12.3.1
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_ADMIN_PASSWORD}
      - GF_SERVER_ROOT_URL=http://localhost:3000
    restart: unless-stopped

  fast_api:
    build: ./project
    command: uvicorn app.main:app --reload --workers 3 --host 0.0.0.0 --port 6000 && sh -c "echo 'Running migrations...' && alembic revision --autogenerate -m 'init tables in database' && alembic upgrade heads &&echo 'Migrations sucess'"
    ports:
      - 8004:6000
    environment:
      - DATABASE_URL=${DB_URL}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      - CLICKHOUSE_DB=${CLICKHOUSE_DB}
    depends_on:
      - db
      - click_house

  db:
    container_name: postgres
    image: postgres:15-alpine
    volumes:
      - ./data/:/var/lib/postgresql/data/
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  pgadmin:
    image: dpage/pgadmin4:9.5
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 80:80
    depends_on:
      - db

  click_house:
    container_name: clickhouse
    image: clickhouse/clickhouse-server:25.11
    environment:
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
      CLICKHOUSE_DB: ${CLICKHOUSE_DB}
    depends_on:
      - db
    ports:
      - 9000:9000
      - 8123:8123
    expose:
      - 8000
